all:
	gcc -o client client.c
	gcc -o server server.c
	gcc -o server2 server2.c

client: client.c
	gcc -o client client.c
server: server.c
	gcc -o server server.c
server2: server2.c
	gcc -o server2 server2.c

clean:
	rm client server server2
